export default () => ({
    entries: [],
    isLoading: true,
    currency: 'EUR',
    readCxData: new Map(),
    predictCxData: new Map(),
    moreInfo: new Map(),
    descriptions: {
        "ada": "Cardano es una plataforma descentralizada que permitirá transferencias de valor complejas y programables de manera segura y escalable. Es una de las primeras cadenas de bloques que se construye en el lenguaje de programación altamente seguro de Haskell. Cardano está desarrollando una plataforma de contrato inteligente que busca ofrecer funciones más avanzadas que cualquier protocolo desarrollado anteriormente. Es la primera plataforma de cadena de bloques que evoluciona a partir de una filosofía científica y un enfoque impulsado por la investigación. El equipo de desarrollo está formado por un gran colectivo mundial de ingenieros e investigadores expertos. El proyecto Cardano es diferente de otros proyectos de cadena de bloques, ya que aborda abiertamente la necesidad de supervisión regulatoria mientras mantiene la privacidad y la protección del consumidor a través de una arquitectura de software innovadora. El protocolo presenta una pila de software de cadena de bloques en capas que es flexible, escalable y se está desarrollando con los estándares de software académicos y comerciales más rigurosos de la industria. ",
        "btc": "Bitcoin es el primer dinero de Internet exitoso basado en tecnología peer-to-peer; por lo que ningún banco central o autoridad está involucrado en la transacción y producción de la moneda Bitcoin. Fue creado por un individuo/grupo anónimo bajo el nombre de Satoshi Nakamoto. El código fuente está disponible públicamente como un proyecto de código abierto, cualquiera puede verlo y ser parte del proceso de desarrollo. Bitcoin está cambiando la forma en que vemos el dinero mientras hablamos. La idea era producir un medio de intercambio, independiente de cualquier autoridad central, que pudiera transferirse electrónicamente de forma segura, verificable e inmutable. Es una moneda de Internet peer-to-peer descentralizada que facilita el pago móvil, tarifas de transacción muy bajas, protege su identidad y funciona en cualquier lugar todo el tiempo sin una autoridad central ni bancos. Bitcoin está diseñado para han creado solo 21 millones de BTC, lo que la convierte en una moneda deflacionaria.",
        "dot": "Polkadot es una plataforma que permite que diversas cadenas de bloques transfieran mensajes, incluido el valor, sin confianza; compartiendo sus características únicas mientras agrupan su seguridad. En resumen, Polkadot es una tecnología multicadena heterogénea escalable. Polkadot es heterogéneo porque es completamente flexible y no hace suposiciones sobre la naturaleza o estructura de las cadenas en la red. Incluso los sistemas o estructuras de datos que no son de cadena de bloques pueden convertirse en paracadenas si cumplen una serie de criterios. Polkadot puede considerarse equivalente a un conjunto de cadenas independientes (por ejemplo, un conjunto que contiene Ethereum, Ethereum Classic, Namecoin y Bitcoin), excepto con adiciones importantes: seguridad agrupada y transacciones entre cadenas sin confianza. Muchas de las paracadenas nativas de Polkadot se escribirán utilizando un SDK de Polkadot Runtime Environment (por ejemplo, Substrate de Parity Technologies).",
        "ltc": "Litecoin es una criptomoneda peer-to-peer creada por Charlie Lee. Fue creado en base al protocolo Bitcoin pero difiere en términos del algoritmo hash utilizado. Litecoin utiliza el algoritmo de minería de prueba de trabajo Scrypt que requiere mucha memoria. Scrypt permite que el hardware de nivel de consumidor, como GPU, extraiga esas monedas. ¿Por qué Litecoin? Litecoin es una criptomoneda que ha evolucionado de Bitcoin después de su propia popularidad en la industria, esta alternativa, o 'altcoin', ha surgido para permitir a los inversores diversificar su paquete de moneda digital, según Investopedia. Litecoin es una de las monedas alternativas más destacadas y fue creada por el ex empleado de Google y director de ingeniería de Coinbase, Charlie Lee. Litecoin fue el primero en alterar Bitcoin y la diferencia más significativa es que Litecoin tarda 2,5 minutos en generar un bloque o transacción, en comparación con los 10 minutos de Bitcoin.",
        "uni": "UNI es el token de gobernanza para Uniswap, un marcador de mercado automatizado DEX en la cadena de bloques de Ethereum. El token UNI permite a los titulares de tokens participar en la gobernanza del protocolo. Las decisiones clave, como el uso de la tesorería o futuras actualizaciones, se pueden decidir a través de un voto de gobierno.",
        "bnb": "Binance Coin es la criptomoneda de la plataforma Binance. Es una plataforma de comercio exclusivamente para criptomonedas. El nombre Binance es una combinación de binario y finanzas. Por lo tanto, el nombre de inicio muestra que solo las criptomonedas pueden intercambiarse entre sí. No es posible intercambiar criptomonedas contra Fiat. La plataforma logró un enorme éxito en muy poco tiempo y se centra en el mercado mundial con sede en Malta. La criptomoneda actualmente tiene un volumen de comercio diario de 1.500 millones a 2.000 millones de dólares estadounidenses y sigue aumentando. En total, solo habrá 200 millones de BNB. Binance utiliza el token estándar ERC20 de Ethereum y lo ha distribuido de la siguiente manera: 50 % vendido en ICO, 40 % para el equipo y 10 % para inversores ángeles.",
        "doge": "Dogecoin es una criptomoneda basada en el popular meme Doge Internet y presenta un Shiba Inu en su logotipo. Dogecoin es una bifurcación de Litecoin. Presentada como una moneda de broma el 6 de diciembre de 2013, Dogecoin desarrolló rápidamente su propia comunidad en línea y alcanzó una capitalización de 60 millones de dólares estadounidenses en enero de 2014. En comparación con otras criptomonedas, Dogecoin tenía un cronograma inicial de producción de monedas rápido: 100 mil millones de monedas estaban en circulación a mediados de 2015, con 5256 millones de monedas adicionales cada año a partir de entonces.",
        "eth": "Ethereum es una plataforma global de código abierto para aplicaciones descentralizadas. En otras palabras, la visión es crear una computadora mundial en la que cualquiera pueda crear aplicaciones de manera descentralizada; mientras que todos los estados y datos se distribuyen y son de acceso público. Ethereum admite contratos inteligentes en los que los desarrolladores pueden escribir código para programar valor digital. Los ejemplos de aplicaciones descentralizadas (dapps) que se basan en Ethereum incluyen tokens, tokens no fungibles, aplicaciones de finanzas descentralizadas, protocolo de préstamo, intercambios descentralizados y mucho más. En Ethereum, todas las transacciones y ejecuciones de contratos inteligentes requieren el pago de una pequeña tarifa. Esta tarifa se llama Gas. En términos técnicos, Gas se refiere a la unidad de medida de la cantidad de esfuerzo computacional requerido para ejecutar una operación o un contrato inteligente. Cuanto más compleja es la operación de ejecución, más gas se requiere para cumplir con esa operación. Las tarifas de gas se pagan íntegramente en Ether (ETH), que es la moneda nativa de la cadena de bloques. El precio del gas puede fluctuar de vez en cuando dependiendo de la demanda de la red.",
        "sol": "Solana (SOL) es una criptomoneda de alto rendimiento basada en el consenso de Prueba de historia (PoH) y Prueba de participación (PoS). Construido por un equipo de ingenieros de redes, Solana pretende convertirse en la infraestructura de cadena de bloques para las aplicaciones modernas de Internet. Solana es una cadena de bloques de propósito general similar a Ethereum. Tiene un fundamento técnico diferente, de modo que los desarrolladores escriben aplicaciones usando Rust en lugar de Solidity o Vyper. Las aplicaciones de usuario final en el ecosistema de Solana incluyen finanzas descentralizadas (DeFi), tokens no fungibles (NFT), mercados, juegos, comercio electrónico y más. Una de sus características más importantes es su escalabilidad en la que Solana puede procesar más de 700,000 transacciones por segundo. Su capacidad de alto rendimiento atrae a los comerciantes de alta frecuencia, encabezada por FTX y Alameda Research.",
        "xrp": "Ripple es el nombre general de la plataforma de criptomonedas, cuyo protocolo transaccional es en realidad XRP, de la misma manera que Ethereum es el nombre de la plataforma que facilita los intercambios en Ether. Al igual que otras criptomonedas, Ripple se basa en la idea de una red de contabilidad distribuida que requiere que varias partes participen en la validación de transacciones, en lugar de una autoridad centralizada singular. Eso facilita las transacciones en todo el mundo, y las tarifas de transferencia son mucho más baratas que las de Bitcoin. A diferencia de otras criptomonedas, las transferencias de XRP son efectivamente inmediatas y no requieren un tiempo de confirmación típico. Ripple fue fundada originalmente por una sola empresa, Ripple Labs, y continúa siendo respaldada por esta, en lugar de por la red más grande de desarrolladores que continúan con el desarrollo de bitcoin. Tampoco tiene una cantidad fluctuante de su moneda en existencia."

    }

})